version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run:
          command: docker-compose up -d api
      - run:
          command: docker-compose up test

workflows:
  build:
    jobs:
      - test